# Generated by Django 5.1.3 on 2024-11-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsky', '0003_chirp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
