# Generated by Django 5.1.3 on 2024-11-26 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsky', '0004_profile_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='chrip_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
